# Generated by Django 5.1.6 on 2025-02-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_text',
            new_name='assignment_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
    ]
