# Generated by Django 5.1.6 on 2025-02-11 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_assignment_text_assignment_assignment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to='assignments.student')),
            ],
        ),
    ]
