# Generated by Django 5.1.6 on 2025-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_student_city_student_gender_teacher_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
