# Generated by Django 5.1.6 on 2025-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_student_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
