# Generated by Django 5.1.6 on 2025-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assignments_submitted/'),
        ),
    ]
