# Generated by Django 5.1.6 on 2025-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_teacher_assignment_name_teacher_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assignments_submitted/'),
        ),
    ]
