# Generated by Django 5.1.6 on 2025-02-19 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_student_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='student_assignment/'),
        ),
        migrations.AddField(
            model_name='scores',
            name='teacher',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to='assignments.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='student_assignment/'),
        ),
    ]
