# Generated by Django 5.1.6 on 2025-02-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_alter_scores_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='teacher',
        ),
    ]
