# Generated by Django 5.1.6 on 2025-02-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_remove_student_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='file_upload',
        ),
    ]
