# Generated by Django 5.1.6 on 2025-03-10 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_remove_teacher_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to='assignments.student'),
        ),
    ]
