# Generated by Django 5.1.6 on 2025-03-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_alter_scores_assignment_alter_scores_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
